### ISSUE TITLE
CHIPS rollout

### ISSUE THREAD

**Issue by dmdabbs** [privacycg/CHIPS#65]
The CHIPS Chrome Design Doc [Testing section](https://docs.google.com/document/d/1wL2lCXpaVOi0cWOn_ehfLFIZQxT3t0SH-ANnZYPEB0I/edit#bookmark=kix.umnmjk8tg4ah) mentions a 'gradual rollout' during M109, which is the current Chrome stable release:

Is the rollout expected to complete during 109, or extend into the next release?

**Comment by krgovind** [comment]
@dmdabbs We did intend for a gradual rollout during M109, but had to hold on those plans due to a bug. We are now targeting a gradual rollout during M110. Please follow the [chromestatus entry](https://chromestatus.com/feature/5179189105786880) for updates.
