### ISSUE TITLE
Clarify Storage Access API Interaction

### ISSUE THREAD

**Issue by bvandersloot-mozilla** [privacycg/CHIPS#81]
The explainer says this about the Storage Access API:

>Partitioned cookies should be accessible regardless of any choices the user has made via the Storage Access API in the given context. Even if the user has rejected or dismissed a prompt for storage access then partitioned cookies should still be accessible (partitioned LocalStorage will still be available in such a context, so blocking access to partitioned cookies would have no effect on user privacy).

It is unclear to me from reading this how cookies set with the Partitioned attribute in a third-party context that is using storage access should behave. (i.e. Iframe B is loaded in page A, gets storage access and runs `document.cookie = "foo=bar; SameSite=None; Secure; Partitioned";`).  Should these cookie be available in a top-level page (i.e. the user opens page B, does that request include the Partitioned cookie from the iframe)?

The CHIPS spec seems to imply the answer is "no" while answering a different question, but the Storage Access API spec would seem to read as "yes". 

Potential re-wordings of this question that all are equivalent:
1. Does the Storage Access API provide access to "first-party" rather than "unpartitioned" data?
2. Do you get access to a different CHIPS partition on a Storage Access API grant?
3. Should the constructed "partition-key" for CHIPS take into consideration the "has storage access" state from the Storage Access API?

@johannhof - thoughts?

**Comment by annevk** [comment]
The idea is that cookies have a "partition key" when they have the Partitioned attribute. E.g., A in your example. The "partition key" always has to match and is irrespective of Storage Access.

Storage Access gives a cross-site document access to SameSite=None cookies of its own site, also taking into account the other aspects that need to match, such as "partition key".

6265-ter will make spelling this out easier.

**Comment by Sarrac3873** [comment]
>  The explainer says this about the Storage Access API:
> 
> >Partitioned cookies should be accessible regardless of any choices the user has made via the Storage Access API in the given context. Even if the user has rejected or dismissed a prompt for storage access then partitioned cookies should still be accessible (partitioned LocalStorage will still be available in such a context, so blocking access to partitioned cookies would have no effect on user privacy).
> 
> It is unclear to me from reading this how cookies set with the Partitioned attribute in a third-party context that is using storage access should behave. (i.e. Iframe B is loaded in page A, gets storage access and runs `document.cookie = "foo=bar; SameSite=None; Secure; Partitioned";`).  Should these cookie be available in a top-level page (i.e. the user opens page B, does that request include the Partitioned cookie from the iframe)?
> 
> The CHIPS spec seems to imply the answer is "no" while answering a different question, but the Storage Access API spec would seem to read as "yes". 
> 
> Potential re-wordings of this question that all are equivalent:
> 1. Does the Storage Access API provide access to "first-party" rather than "unpartitioned" data?
> 2. Do you get access to a different CHIPS partition on a Storage Access API grant?
> 3. Should the constructed "partition-key" for CHIPS take into consideration the "has storage access" state from the Storage Access API?
> 
> @johannhof - thoughts?

**Comment by johannhof** [comment]
Yeah +1 to Anne, I can see how this isn't clearly spelled out lacking a proper spec (WIP), but I'm also not sure why "unpartitioned" is particularly wrong. CHIPS gives cookies a partition key, and cookies are always accessible when the partition key matches the partition you're in. What SAA does is unlock cross-site cookies without partition key. It does not change the partition context you're in. (This is one of the nice properties of explicit partitioning, it's easy to tell where the cookies end up).

**Comment by bvandersloot-mozilla** [comment]
"Unpartitioned" is correct then. "first-party" cookies would include A's (A,A,samesite) cookies IMO, so that would be incorrect.

I agree that it is the best interpretation.
