### ISSUE TITLE
CHIPS changing with new path forward?

### ISSUE THREAD

**Issue by dmdabbs** [privacycg/CHIPS#91]
Under the "post-deprecation" new path, based upon user consent, will a cross-site embedded resource still be able to set a partitioned cookie for the use cases described when the user has opted to not enable (unpartitioned) cross-site cookies?

**Comment by krgovind** [comment]
Thanks for the question, @dmdabbs. Yes, cross-site embedded resources will indeed still be able to set a partitioned cookie when the user has opted to not enable (unpartitioned) cross-site cookies?
